### ISSUE TITLE
Likes added

### ISSUE THREAD

**Issue by WJLiddy** [nanflasted/C-SPAN#1]
Likes not generated in newTweet when "likes" argument is set to true. Same thing happens for newReply.

Error:

insert into votes (id,lid,cid) values (?,?,?);
2016-12-09 00:02:54.536081
exception: Database Insertion Error at genVotes
  File "dbpopl.py", line 418, in genLikes
    raise Exception("Database Insertion Error at genVotes")
stack: None
Traceback (most recent call last):
  File "dbpopl.py", line 418, in genLikes
    raise Exception("Database Insertion Error at genVotes")
Exception: Database Insertion Error at genVotes
None
2016-12-09 00:02:54.594214
exception: NOT NULL constraint failed: votes.votes
  File "dbmngr.py", line 129, in insertMany
    c.executemany(execstr,entrylist)
stack: None
Traceback (most recent call last):
  File "dbmngr.py", line 129, in insertMany
    c.executemany(execstr,entrylist)
IntegrityError: NOT NULL constraint failed: votes.votes
None

**Comment by nanflasted** [comment]
Rip likes.

**Comment by nanflasted** [comment]
Aww ... I ... this.
